# Generated by Django 3.1.4 on 2021-04-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookTable',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploadTime', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PodcastParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongTable',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploadTime', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PodcastTable',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploadTime', models.PositiveIntegerField()),
                ('host', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(to='AudioServer.PodcastParticipants')),
            ],
        ),
    ]
