# Generated by Django 3.1.4 on 2021-04-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongTable',
            new_name='Song',
        ),
        migrations.DeleteModel(
            name='AudioBookTable',
        ),
        migrations.RemoveField(
            model_name='podcasttable',
            name='participants',
        ),
        migrations.DeleteModel(
            name='PodcastParticipants',
        ),
        migrations.DeleteModel(
            name='PodcastTable',
        ),
    ]
