# Generated by Django 3.1.4 on 2021-04-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioServer', '0003_audiobook_podcast_podcastparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='title',
            field=models.FileField(upload_to='audiobook/'),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='uploadTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='name',
            field=models.FileField(upload_to='podcast/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploadTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploadTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
