# Generated by Django 3.1.4 on 2021-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioServer', '0008_auto_20210409_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.FileField(upload_to='audiobook/')),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploadTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='podcast/')),
                ('duration', models.PositiveIntegerField()),
                ('uploadTime', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(to='AudioServer.PodcastParticipant')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='songs/')),
                ('duration', models.PositiveIntegerField()),
                ('uploadTime', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(to='AudioServer.PodcastParticipant')),
            ],
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
