# Generated by Django 3.1.4 on 2021-04-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioServer', '0009_auto_20210409_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='host',
        ),
        migrations.RemoveField(
            model_name='song',
            name='participants',
        ),
    ]
