# Generated by Django 3.1.4 on 2021-04-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioServer', '0014_auto_20210410_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
